config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :users, only: [:show, :index, :update] do
    resources :friend_requests, only: [:create, :index, :destroy]
    resources :friendships, only: [:create, :index, :destroy], path: :friends, as: :friends
    resources :posts, only: [:create, :index, :destroy] do
      resources :comments, only: [:new, :create, :index, :destroy]
      resources :likes, only: [:create]
    end
    resources :comments, only: [:create, :destroy, :index] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
    resources :likes, only: [:index, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recieved_requests, class_name: "FriendRequest", foreign_key: "invitee_id", dependent: :destroy
  has_many :sent_requests, class_name: "FriendRequest", foreign_key: "inviter_id", dependent: :destroy
  has_many :requester_friendships, class_name: "Friendship", foreign_key: :requester_id, dependent: :destroy
  has_many :requester_friends, through: :requester_friendships, source: :requestee
  has_many :requestee_friendships, class_name: "Friendship", foreign_key: :requestee_id, dependent: :destroy
  has_many :requestee_friends, through: :requestee_friendships, source: :requester
  has_many :posts, foreign_key: :author, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :likeable, source_type: 'Post'
  has_many :comments, foreign_key: :author, dependent: :destroy
  has_many :liked_comments, through: :likes, source: :likeable, source_type: 'Comment'
  has_attached_file :avatar, default_url: "avatar.jpeg",  styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  validates :first_name, presence: true, length: { maximum: 250 }
  validates :last_name, presence:true, length: { maximum: 250 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/                  

  def full_name
    self.first_name + " " + self.last_name
  end

  def friends
    User.where(id: friend_ids)
  end

  def friendship(user)
    Friendship.where(requester_id: id, requestee_id: user.id).or(Friendship.where(requester_id: user.id, requestee_id: id)).first
  end

  def friendships
    Friendship.where(requester_id: id).or(Friendship.where(requestee_id: id))
  end

  def requests
    FriendRequest.where(inviter_id: id).or(FriendRequest.where(invitee_id: id))
  end

  def feed
    Post.where(author_id: id).or(Post.where(author_id: friend_ids)).order(created_at: :desc)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.token = auth.credentials.token
      user.expires = auth.credentials.expires
      user.expires_at = auth.credentials.expires_at
      user.refresh_token = auth.credentials.refresh_token
    end
  end

  private
    def friend_ids
      friendships.map do |f|
        f.requester_id == self.id ? f.requestee_id : f.requester_id
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    auth = request.env["omniauth.auth"]
    user = User.find_by(provider: auth["provider"], uid: auth["uid"])
    unless user
      user = User.find_by(email: auth["info"]["email"])
      user.assign_attributes(provider: auth["provider"], uid: auth["uid"]) if user
    end
    unless user
      name = auth["info"]["name"].split(" ")
      user = User.new(email: auth["info"]["email"], first_name: name[0], last_name: name[1], provider: auth["provider"], uid: auth["uid"], password: Devise.friendly_token)
    end
    user.save!
    sign_in(:user, user)
    

    flash[:success] = "Signed in with Google"
    redirect_to user_posts_path(user.id)
end    
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  #protected

  def after_resetting_password_path_for(resource)
    user_posts_path(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    resource
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  #DELETE /resource/sign_out
  def destroy
    current_user.remember_me = false
    super
    flash[:notice] = "Signed out. Please sign out of your Google account to ensure account security."
  end

    protected

    def after_sign_in_path_for(resource)
      user_posts_path(resource)
    end

    def after_sign_out_path_for(resource)
      root_path
    end



  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        if params[:search]
            @users = search(search_params)
        else
            @users = User.all
        end
        respond_to do |format|
            format.js
            format.html
        end
    end
    def show
        @user = User.find(params[:id])
        @posts = @user.posts.order(:created_at)
        @button = button_type
    end

    def update
        @user = current_user
        @posts = @user.posts.order(:created_at)
        if update_params.empty?
            flash.now[:warning] = "Please choose a file to upload"
            render 'users/show'
            return
        end
        if @user.update_attributes(update_params)
            flash[:success] = "Avatar Uploaded"
            redirect_to current_user
        else
            flash.now[:warning] = "Unable to upload file"
            render 'users/show'
        end
    end 

    private
        def update_params
            begin
                params.require(:user).permit(:avatar)
            rescue
                {}
            end
        end

        def search_params
            params.require(:search).permit(:input)
        end

        def button_type
            case true
            when current_user == @user
                return nil
            when current_user.friends.include?(@user)
                return 'unfriend'
            when current_user.sent_requests.where(invitee_id: @user.id).present?
                return 'sent_request'
            when current_user.recieved_requests.where(inviter_id: @user.id).present?
                return 'recieved_request'
            else
                return 'friend_request'
            end
        end

        def search(search_params)
            keywords = search_params[:input].split(" ")
            return User.all if keywords.empty?
            if keywords.length == 2
                result = User.where('LOWER(first_name) LIKE LOWER(?) AND LOWER(last_name) LIKE LOWER(?)', keywords[0], keywords[1])
                result = User.where('LOWER(last_name) LIKE LOWER(?) AND LOWER(first_name) LIKE LOWER(?)', keywords[0], keywords[1]) if result.empty?
                result = User.where(query(keywords)) if result.empty?
            else
                result = User.where(query(keywords))
            end
            result
          end

        def query(keywords)
            query = [""]
            keywords.each do |keyword|
                query[0] += "LOWER(first_name) LIKE LOWER(?) OR LOWER(last_name) LIKE LOWER(?) OR "
                query.append(keyword, keyword)
            end
            query[0].delete_suffix!('OR ')
            query
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar_upload_form.html.erb
<%= form_with url: user_path, method: :patch, scope: :user, local: true, multipart: true, html: {class: "pt-2", id: "upload-form", style: "display: none"} do |f| %>
  <div class="field">
    <%= f.file_field :avatar %>
  </div>
  <div class="btn-group">
    <%= button_tag "Hide", type: "button" , onclick: "hide_upload();", class: "btn btn-secondary btn-sm", id: "hide-button" %>
    <%= f.submit 'Upload', class: "btn btn-primary btn-sm", id: "blue-button" %>
  </div>
<% end %>

app/views/users/_avatar_upload_link.html.erb
<%= link_to "Change avatar", '#', id: "upload-link", onclick: "show_upload();", remote: true %>

app/views/users/_user.html.erb
<div class="container">
    <div class="profile-container">
        <% if user == current_user %>
            <div class="row">
                <div class = "col">
                    <div class="pull-right social-action dropdown">
                        <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                            <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu m-t-xs">
                            <li> <%= link_to "Cancel my account", registration_path(user), data: { confirm: "Are you sure?" }, method: :delete %>
                        </ul>
                    </div>
                </div>  
            </div>
        <% end %>
        <div class="row">
            <div class="col-12 center-block text-center pt-4">
                <%= image_tag user.avatar.url(:medium) %>
            </div>
        </div>
        <% if user == current_user %>
            <div class="row", id="upload-container">
                <div class="col-12 center-block text-center">
                    <%= render 'users/avatar_upload_link' %>
                    <%= render 'users/avatar_upload_form', user: user %>
                </div>        
            </div>
        <% end %>
        <div class="row">
            <div class="col-12 center-block text-center">
                <h1><%= @user.full_name %></h1>
            </div> 
        </div>
        <div class="row">
            <div class = "col-12 center-block text-center">
                <h6><%= @user.email %></h6>
            </div>
        </div>
        <div class="row bottom-buffer">
            <div class="col-12 center-block text-center">
                <div id = 'request-button-container'>
                    <% case @button %>
                    <% when 'friend_request' %>
                        <%= render 'friend_requests/friend_request_button', user_id: @user.id %>
                    <% when 'sent_request' , "recieved_request" %>
                        <div id= pending-request-message>
                            <p>Pending request</p>
                        </div>
                    <% when 'unfriend' %>
                        <div id = unfriend-button>
                            <%= button_to "Unfriend", user_friend_path(current_user.id, current_user.friendship(@user).id), { method: :delete, remote: true, class: 'btn', id: 'hide-button'} %>
                        </div>
                    <% end %>
                </div>
            </div> 
        </div>
    </div> 
</div>

app/views/users/_user_widgets.html.erb
<% users.each do |u| %>
    <div class="row align-items-center pt-2 pb-2" id="user-widget">
        <div class='col'>
            <%= image_tag u.avatar.url(:square) %>
        </div>
        <div class="col d-flex text-left">
            <%= link_to u.full_name, u %>
        </div>  
    </div>
<% end %>

app/views/users/index.html.erb
<div class="md-form mt-0">
    <%= form_with url: users_path, method: :get, scope: :search do |f| %>
        <%= f.text_field :input, placeholder: "Search" %>
        <%= f.submit "Search", class: "btn btn-sm", id: "blue-button"%>
    <% end %>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-2", , id="user-list">
            <%= render 'users/user_widgets', users: @users %>
        </div> 
    </div>
    
</div>

app/views/users/index.js.erb
$('#user-list').empty().append("<%= j render 'users/user_widgets', users: @users %>");

app/views/users/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<%= render @user %>

<div class="container">
    <div class="row">
        <div class="col-sm-2">
            <div class="container">
                <div class="row">
                    <h2>Friends</h2>
                </div>
                <%= render 'users/user_widgets', users: @user.friends %>
            </div> 
        </div>
        <div class="col-md-7", id='feed'>
             <% if !@posts.empty? %>
                <div class = 'posts-container'>
                    <div class = 'posts'>
                        <%= render @posts %>
                    </div>
                </div>
            <% else %>
                <h2>No posts yet. Why not create one?</h2>
            <% end %>
        </div>
    </div>
</div>