config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :users, only: [:show, :index, :update] do
    resources :friend_requests, only: [:create, :index, :destroy]
    resources :friendships, only: [:create, :index, :destroy], path: :friends, as: :friends
    resources :posts, only: [:create, :index, :destroy] do
      resources :comments, only: [:new, :create, :index, :destroy]
      resources :likes, only: [:create]
    end
    resources :comments, only: [:create, :destroy, :index] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
    resources :likes, only: [:index, :destroy]
  end
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"

  
  validate :non_duplicate
  validate :not_friends
  validates :inviter, presence: true
  validates :invitee, presence: true
  

  def non_duplicate
    if FriendRequest.where(inviter_id: inviter_id, invitee_id: invitee_id).exists? || FriendRequest.where(inviter_id: invitee_id, invitee_id: inviter_id).exists?
      errors.add(:invitee_id, "Duplicate request")
    end
  end

  def not_friends
    begin
      if User.find(self.inviter_id).friends.include?(User.find(self.invitee_id))
        errors.add(:invitee_id, "Already friends")
      end
    rescue
    end
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:index]

    def index
        @requests = User.find(params[:user_id]).recieved_requests
    end

    def create
        @request = current_user.sent_requests.new(request_params)
        if @request.save
            flash.now[:success] = "Friend request sent"
        else
            flash.now[:danger] = "Request unable to be sent"
        end
        respond_to do |format|
            format.js
        end
    end

    def destroy
        begin
            @request = current_user.sent_requests.find(params[:id])
            @request.destroy
            flash.now[:success] = "Request rescinded"
        rescue ActiveRecord::RecordNotFound
            flash.now[:danger] = "No request found"
        end        
    end


    private
        def request_params
            params.require(:friend_request).permit(:invitee_id)
        end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_friend_request.html.erb
<div class="dropdown-item">
    <%= link_to friend_request.inviter.full_name, friend_request.inviter %>
    <div id = <%= friend_request.id %>-request class="btn-group" role="group" aria-label="Basic example">
        <%= button_to "Accept", user_friends_path(current_user), { class: "btn btn-secondary  mx-2", id: 'green-button', method: :post, remote: true, params: {friendship: { requestee_id: friend_request.inviter.id }}}  %>
        <%= button_to "Decline", '#', class: "btn btn-secondary", id: 'red-button' %>
    </div>
</div>

app/views/friend_requests/_friend_request_button.html.erb
<div id = friend-request-button>
    <%= button_to "Send Friend Request", user_friend_requests_path(current_user.id), {method: :post, remote: true, class: 'btn', id: 'blue-button',  params: {friend_request: {invitee_id: user_id }}}  %>
    <%# byebug %>
</div>

app/views/friend_requests/create.js.erb
$('#friend-request-button').empty().prepend("<p>Friend Request Sent</p>");

app/views/friend_requests/index.html.erb
<h1>Pending Requests</h1>
<%= render @requests %>