config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :users, only: [:show, :index, :update] do
    resources :friend_requests, only: [:create, :index, :destroy]
    resources :friendships, only: [:create, :index, :destroy], path: :friends, as: :friends
    resources :posts, only: [:create, :index, :destroy] do
      resources :comments, only: [:new, :create, :index, :destroy]
      resources :likes, only: [:create]
    end
    resources :comments, only: [:create, :destroy, :index] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
    resources :likes, only: [:index, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy


  validates :author, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :correct_user, only: [:index]

    def index
        @posts = current_user.feed
    end

    def create
        @post = current_user.posts.new(post_params)
        if @post.save
            flash[:success] = "Posted"
        else
            flash[:danger] = "Post cannot be created"
        end
        respond_to do |format|
            format.js
        end
    end

    def destroy
        begin
            @post = current_user.posts.find(params[:id])
            @post.destroy
            flash[:success] = "Post deleted"
        rescue ActiveRecord::RecordNotFound
            flash[:danger] = "No post found"
        end
        respond_to do |format|
            format.js
        end
    end

    private
        def post_params
            params.require(:post).permit(:content)
        end

        def belongs_to_user(object)
            object.author_id == current_user.id
        end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_create_form.html.erb
<%= form_with url: polymorphic_path([current_user, Post.new]), scope: :post do |f| %>
<div class = 'd-flex flex-column'>
    <%= f.text_area :content, placeholder: 'What are you thinking about?', class: 'p2', size: '20x5'; %>
    <%= f.submit "Post", class: "btn btn-primary", id: 'blue-button' %>
</div>
    
<% end %>

app/views/posts/_delete_button.html.erb
<%= link_to "Delete Post", user_post_path(current_user, post), method: :delete, remote: true %>

app/views/posts/_feed.html.erb
<div class = "feed">
        <% if @posts.empty? %>
                <div class = 'no-content'>
                        <h2>Nothing in your timeline. Try adding some friends and posting some content.</h2>
                </div>
        <% end %>
        <%= render @posts %>
</div>

app/views/posts/_post.html.erb
<div class="social-feed-separated", id=<%= post.id.to_s %>>
    <div class="social-avatar">
        <%= image_tag post.author.avatar.url(:square) %>
    </div>

    <div class="social-feed-box">
        <% if current_user == post.author %>
            <div class="pull-right social-action dropdown">
                <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                    <i class="fa fa-angle-down"></i>
                </button>
                <ul class="dropdown-menu m-t-xs">
                    <li> <%= render 'posts/delete_button', post: post %>
                </ul>
            </div>
        <% end %>
        <div class="social-avatar">
            <%= link_to post.author.full_name, post.author %>
            <small class="text-muted">posted <%= time_ago_in_words(post.created_at) %> ago</small>
        </div>
        <div class="social-body">
            <p class='post-content'>
                <%= post.content %>
            </p>
            <div class="btn-group btn-group-sm", id = '<%= post.class.to_s %>-<%= post.id.to_s %>-buttons' >
                <%# <button class="btn btn-white btn-xs"><i class="fa fa-thumbs-up"></i> Like this!</button> %>
                <div id='<%= post.class %>-<%= post.id %>-likes'>
                    <%= render 'likes/likes_button', likeable: post %>
                </div>
                <%= render 'comments/create_link', commentable: post%>
                <%# <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button> %>
                <%# <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button> %>
            </div>
            <%= content_tag "div", id: "#{post.class}-#{post.id}-new-comment-container" do %>
            <% end %>
        </div>
        <div class="social-footer">
            <%= content_tag "div", id: "#{post.class}-#{post.id}-comments-links" do %>
                <% if post.comments.count > 0 %>
                    <%= link_to "Show #{pluralize(post.comments.count, 'comment')}", user_post_comments_path(post.author, post.id), id: "#{post.class}-#{post.id}-show-comments", remote: true %>
                    <%= link_to "Hide Comments", '#', onclick: "hide_comments(#{post.id});", id: "#{post.class}-#{post.id}-hide-comments", style: "display: none;", remote: true %>
                <% end %>
            <% end %>
            <%= content_tag "div", id: "#{post.class}-#{post.id}-comments" do %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/create.js.erb
$('#feed').prepend('<%= j render(@post) %>');
$('.no-content').remove()
$('#post_content').val('');

app/views/posts/destroy.js.erb
$('#<%= @post.id %>').remove();

app/views/posts/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <div class="row">
        <div class="col-md-7", id='feed'>
            <div class="new-post-form">
                <%= render 'posts/create_form' %>
            </div>
            <%= render @posts %>
        </div>
    </div>
</div>